#!/usr/bin/expect -f

set tutor [lindex $argv 0]
set executable [lindex $argv 1]
set sshvmextra [lindex $argv 2]
set username [lindex $argv 3]

if { $sshvmextra == 1 } {
	spawn ssh $username@$tutor
	expect "> "
	
	# note: tutor-login should be an alias for 
	# logging into the VM on the host
	send "tutor-login\r"
} else {
	spawn ssh tuser@$tutor
}

# tutor expects passwordless key-based authentication
expect "$ "
send "cd executables\r"
expect "$ "

send "mtip -f $executable && exit\r"
expect "Using board # 1"
send "\r"
expect "> "
send "~d"
expect "> "
interact
